HTTP/1.1 200 OK
X-Powered-By: Express
Access-Control-Allow-Origin: *
Content-Type: application/json; charset=utf-8
Content-Length: 52
ETag: W/"34-B1BEMsmItvUMFhlD7Maftwvy/Xk"
Date: Wed, 21 Dec 2022 18:43:23 GMT
Connection: close

[
  {
    "name": "AslanSN",
    "id": "63a3514df7b319ac9448cef1"
  }
]